name: Traefik
description: |
  Traefik clustered/HA active load balancer
version: v1.4.5-rancher2
category: Load Balancing
maintainer: "romracer <romracer@gmail.com>"
minimum_rancher_version: v1.4.0
projectURL: https://github.com/romracer/romracer-traefik
