version: '2'
services:
 front:
    image: mailu/nginx:${VERSION}
    restart: always
    labels: 
     io.rancher.container.pull_image: always
     com.docker.compose.service: front
    environment:
     BIND_ADDRESS4: ${BIND_ADDRESS4}
     COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
     DOMAIN: ${DOMAIN}
     ADMIN: ${EXPOSE_ADMIN}
     FETCHMAIL_DELAY: ${FETCHMAIL_DELAY}
     HOSTNAMES: ${HOSTNAMES}
     MESSAGE_SIZE_LIMIT: ${MESSAGE_SIZE_LIMIT}
     POSTMASTER: ${POSTMASTER}
     RELAYHOST: ${RELAYHOST}
     RELAYNETS: ${RELAYNETS}
     ROOT: ${ROOT}
     SECRET_KEY: ${SECRET_KEY}
     VERSION: ${VERSION}
     WEBMAIL: ${WEBMAIL}
     WEBDAV: ${WEBDAV}
     TLS_FLAVOR: ${TLS_FLAVOR}
     PASSWORD_SCHEME: ${PASSWORD_SCHEME}
     RECIPIENT_DELIMITER: ${RECIPIENT_DELIMITER}
     AUTH_RATELIMIT: ${AUTH_RATELIMIT}
     DISABLE_STATISTICS: "true"
     DMARC_RUA: postmaster
     DMARC_RUF: postmaster
     WELCOME: "false"
     WEB_ADMIN: "/admin"
     WEB_WEBMAIL: "/webmail"
    expose:
      - "80"
      - "443"
    ports:
      - "${BIND_ADDRESS4}:110:110"
      - "${BIND_ADDRESS4}:143:143"
      - "${BIND_ADDRESS4}:993:993"
      - "${BIND_ADDRESS4}:995:995"
      - "${BIND_ADDRESS4}:25:25"
      - "${BIND_ADDRESS4}:465:465"
      - "${BIND_ADDRESS4}:587:587"
    volumes:
      - "${ROOT}/certs:/certs"
 redis:
    image: redis:alpine
    restart: always
    labels: 
     io.rancher.container.pull_image: always
     com.docker.compose.service: redis
    environment:
     BIND_ADDRESS4: ${BIND_ADDRESS4}
     COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
     DOMAIN: ${DOMAIN}
     ADMIN: ${EXPOSE_ADMIN}
     FETCHMAIL_DELAY: ${FETCHMAIL_DELAY}
     HOSTNAMES: ${HOSTNAMES}
     MESSAGE_SIZE_LIMIT: ${MESSAGE_SIZE_LIMIT}
     POSTMASTER: ${POSTMASTER}
     RELAYHOST: ${RELAYHOST}
     RELAYNETS: ${RELAYNETS}
     ROOT: ${ROOT}
     SECRET_KEY: ${SECRET_KEY}
     VERSION: ${VERSION}
     WEBMAIL: ${WEBMAIL}
     WEBDAV: ${WEBDAV}
     TLS_FLAVOR: ${TLS_FLAVOR}
     PASSWORD_SCHEME: ${PASSWORD_SCHEME}
     RECIPIENT_DELIMITER: ${RECIPIENT_DELIMITER}
     AUTH_RATELIMIT: ${AUTH_RATELIMIT}
     DISABLE_STATISTICS: "true"
     DMARC_RUA: postmaster
     DMARC_RUF: postmaster
     WELCOME: "false"
     WEB_ADMIN: "/admin"
     WEB_WEBMAIL: "/webmail"
    volumes:
      - "${ROOT}/redis:/data"
 imap:
    image: mailu/dovecot:${VERSION}
    restart: always
    labels: 
     io.rancher.container.pull_image: always
     com.docker.compose.service: imap
    environment:
     BIND_ADDRESS4: ${BIND_ADDRESS4}
     COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
     DOMAIN: ${DOMAIN}
     ADMIN: ${EXPOSE_ADMIN}
     FETCHMAIL_DELAY: ${FETCHMAIL_DELAY}
     HOSTNAMES: ${HOSTNAMES}
     MESSAGE_SIZE_LIMIT: ${MESSAGE_SIZE_LIMIT}
     POSTMASTER: ${POSTMASTER}
     RELAYHOST: ${RELAYHOST}
     RELAYNETS: ${RELAYNETS}
     ROOT: ${ROOT}
     SECRET_KEY: ${SECRET_KEY}
     VERSION: ${VERSION}
     WEBMAIL: ${WEBMAIL}
     WEBDAV: ${WEBDAV}
     TLS_FLAVOR: ${TLS_FLAVOR}
     PASSWORD_SCHEME: ${PASSWORD_SCHEME}
     RECIPIENT_DELIMITER: ${RECIPIENT_DELIMITER}
     AUTH_RATELIMIT: ${AUTH_RATELIMIT}
     DISABLE_STATISTICS: "true"
     DMARC_RUA: postmaster
     DMARC_RUF: postmaster
     WELCOME: "false"
     WEB_ADMIN: "/admin"
     WEB_WEBMAIL: "/webmail"
    depends_on:
      - front
    volumes:
      - "${ROOT}/data:/data"
      - "${ROOT}/mail:/mail"
      - "${ROOT}/overrides:/overrides"
 smtp:
    image: mailu/postfix:${VERSION}
    restart: always
    labels: 
     io.rancher.container.pull_image: always
     com.docker.compose.service: smtp
     io.rancher.scheduler.affinity:container_label: io.rancher.stack_service.name=$${stack_name}/front
    environment:
     BIND_ADDRESS4: ${BIND_ADDRESS4}
     COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
     DOMAIN: ${DOMAIN}
     ADMIN: ${EXPOSE_ADMIN}
     FETCHMAIL_DELAY: ${FETCHMAIL_DELAY}
     HOSTNAMES: ${HOSTNAMES}
     MESSAGE_SIZE_LIMIT: ${MESSAGE_SIZE_LIMIT}
     POSTMASTER: ${POSTMASTER}
     RELAYHOST: ${RELAYHOST}
     RELAYNETS: ${RELAYNETS}
     ROOT: ${ROOT}
     SECRET_KEY: ${SECRET_KEY}
     VERSION: ${VERSION}
     WEBMAIL: ${WEBMAIL}
     WEBDAV: ${WEBDAV}
     TLS_FLAVOR: ${TLS_FLAVOR}
     PASSWORD_SCHEME: ${PASSWORD_SCHEME}
     RECIPIENT_DELIMITER: ${RECIPIENT_DELIMITER}
     AUTH_RATELIMIT: ${AUTH_RATELIMIT}
     DISABLE_STATISTICS: "true"
     DMARC_RUA: postmaster
     DMARC_RUF: postmaster
     WELCOME: "false"
     WEB_ADMIN: "/admin"
     WEB_WEBMAIL: "/webmail"
    depends_on:
      - front
    volumes:
      - "${ROOT}/data:/data"
      - "${ROOT}/overrides:/overrides"
 antispam:
    image: mailu/rspamd:${VERSION}
    restart: always
    labels: 
     io.rancher.container.pull_image: always
     com.docker.compose.service: antispam
    environment:
     BIND_ADDRESS4: ${BIND_ADDRESS4}
     COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
     DOMAIN: ${DOMAIN}
     ADMIN: ${EXPOSE_ADMIN}
     FETCHMAIL_DELAY: ${FETCHMAIL_DELAY}
     HOSTNAMES: ${HOSTNAMES}
     MESSAGE_SIZE_LIMIT: ${MESSAGE_SIZE_LIMIT}
     POSTMASTER: ${POSTMASTER}
     RELAYHOST: ${RELAYHOST}
     RELAYNETS: ${RELAYNETS}
     ROOT: ${ROOT}
     SECRET_KEY: ${SECRET_KEY}
     VERSION: ${VERSION}
     WEBMAIL: ${WEBMAIL}
     WEBDAV: ${WEBDAV}
     TLS_FLAVOR: ${TLS_FLAVOR}
     PASSWORD_SCHEME: ${PASSWORD_SCHEME}
     RECIPIENT_DELIMITER: ${RECIPIENT_DELIMITER}
     AUTH_RATELIMIT: ${AUTH_RATELIMIT}
     DISABLE_STATISTICS: "true"
     DMARC_RUA: postmaster
     DMARC_RUF: postmaster
     WELCOME: "false"
     WEB_ADMIN: "/admin"
     WEB_WEBMAIL: "/webmail"
    depends_on:
      - front
    volumes:
      - "${ROOT}/filter:/var/lib/rspamd"
      - "$ROOT/dkim:/dkim"
      - "$ROOT/overrides/rspamd:/etc/rspamd/override.d"
 antivirus:
    image: mailu/clamav:${VERSION}
    restart: always
    labels: 
     io.rancher.container.pull_image: always
     com.docker.compose.service: antivirus
    environment:
     BIND_ADDRESS4: ${BIND_ADDRESS4}
     COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
     DOMAIN: ${DOMAIN}
     ADMIN: ${EXPOSE_ADMIN}
     FETCHMAIL_DELAY: ${FETCHMAIL_DELAY}
     HOSTNAMES: ${HOSTNAMES}
     MESSAGE_SIZE_LIMIT: ${MESSAGE_SIZE_LIMIT}
     POSTMASTER: ${POSTMASTER}
     RELAYHOST: ${RELAYHOST}
     RELAYNETS: ${RELAYNETS}
     ROOT: ${ROOT}
     SECRET_KEY: ${SECRET_KEY}
     VERSION: ${VERSION}
     WEBMAIL: ${WEBMAIL}
     WEBDAV: ${WEBDAV}
     TLS_FLAVOR: ${TLS_FLAVOR}
     PASSWORD_SCHEME: ${PASSWORD_SCHEME}
     RECIPIENT_DELIMITER: ${RECIPIENT_DELIMITER}
     AUTH_RATELIMIT: ${AUTH_RATELIMIT}
     DISABLE_STATISTICS: "true"
     DMARC_RUA: postmaster
     DMARC_RUF: postmaster
     WELCOME: "false"
     WEB_ADMIN: "/admin"
     WEB_WEBMAIL: "/webmail"
    volumes:
      - "${ROOT}/filter:/data"
 webdav:
    image: "mailu/${WEBDAV}:${VERSION}"
    restart: always
    labels: 
     io.rancher.container.pull_image: always
     com.docker.compose.service: webdav
    environment:
     BIND_ADDRESS4: ${BIND_ADDRESS4}
     COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
     DOMAIN: ${DOMAIN}
     ADMIN: ${EXPOSE_ADMIN}
     FETCHMAIL_DELAY: ${FETCHMAIL_DELAY}
     HOSTNAMES: ${HOSTNAMES}
     MESSAGE_SIZE_LIMIT: ${MESSAGE_SIZE_LIMIT}
     POSTMASTER: ${POSTMASTER}
     RELAYHOST: ${RELAYHOST}
     RELAYNETS: ${RELAYNETS}
     ROOT: ${ROOT}
     SECRET_KEY: ${SECRET_KEY}
     VERSION: ${VERSION}
     WEBMAIL: ${WEBMAIL}
     WEBDAV: ${WEBDAV}
     TLS_FLAVOR: ${TLS_FLAVOR}
     PASSWORD_SCHEME: ${PASSWORD_SCHEME}
     RECIPIENT_DELIMITER: ${RECIPIENT_DELIMITER}
     AUTH_RATELIMIT: ${AUTH_RATELIMIT}
     DISABLE_STATISTICS: "true"
     DMARC_RUA: postmaster
     DMARC_RUF: postmaster
     WELCOME: "false"
     WEB_ADMIN: "/admin"
     WEB_WEBMAIL: "/webmail"
    volumes:
      - "${ROOT}/dav:/data"
 admin:
    image: mailu/admin:${VERSION}
    restart: always
    labels: 
     io.rancher.container.pull_image: always
     com.docker.compose.service: admin
    environment:
     BIND_ADDRESS4: ${BIND_ADDRESS4}
     COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
     DOMAIN: ${DOMAIN}
     ADMIN: ${EXPOSE_ADMIN}
     FETCHMAIL_DELAY: ${FETCHMAIL_DELAY}
     HOSTNAMES: ${HOSTNAMES}
     MESSAGE_SIZE_LIMIT: ${MESSAGE_SIZE_LIMIT}
     POSTMASTER: ${POSTMASTER}
     RELAYHOST: ${RELAYHOST}
     RELAYNETS: ${RELAYNETS}
     ROOT: ${ROOT}
     SECRET_KEY: ${SECRET_KEY}
     VERSION: ${VERSION}
     WEBMAIL: ${WEBMAIL}
     WEBDAV: ${WEBDAV}
     TLS_FLAVOR: ${TLS_FLAVOR}
     PASSWORD_SCHEME: ${PASSWORD_SCHEME}
     RECIPIENT_DELIMITER: ${RECIPIENT_DELIMITER}
     AUTH_RATELIMIT: ${AUTH_RATELIMIT}
     DISABLE_STATISTICS: "true"
     DMARC_RUA: postmaster
     DMARC_RUF: postmaster
     WELCOME: "false"
     WEB_ADMIN: "/admin"
     WEB_WEBMAIL: "/webmail"
    depends_on:
      - redis
    volumes:
      - "${ROOT}/data:/data"
      - "${ROOT}/dkim:/dkim"
      - /var/run/docker.sock:/var/run/docker.sock:ro
 webmail:
    image: "mailu/${WEBMAIL}:${VERSION}"
    restart: always
    labels: 
     io.rancher.container.pull_image: always
     com.docker.compose.service: webmail
    environment:
     BIND_ADDRESS4: ${BIND_ADDRESS4}
     COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
     DOMAIN: ${DOMAIN}
     ADMIN: ${EXPOSE_ADMIN}
     FETCHMAIL_DELAY: ${FETCHMAIL_DELAY}
     HOSTNAMES: ${HOSTNAMES}
     MESSAGE_SIZE_LIMIT: ${MESSAGE_SIZE_LIMIT}
     POSTMASTER: ${POSTMASTER}
     RELAYHOST: ${RELAYHOST}
     RELAYNETS: ${RELAYNETS}
     ROOT: ${ROOT}
     SECRET_KEY: ${SECRET_KEY}
     VERSION: ${VERSION}
     WEBMAIL: ${WEBMAIL}
     WEBDAV: ${WEBDAV}
     TLS_FLAVOR: ${TLS_FLAVOR}
     PASSWORD_SCHEME: ${PASSWORD_SCHEME}
     RECIPIENT_DELIMITER: ${RECIPIENT_DELIMITER}
     AUTH_RATELIMIT: ${AUTH_RATELIMIT}
     DISABLE_STATISTICS: "true"
     DMARC_RUA: postmaster
     DMARC_RUF: postmaster
     WELCOME: "false"
     WEB_ADMIN: "/admin"
     WEB_WEBMAIL: "/webmail"
    volumes:
      - "${ROOT}/webmail:/data"
 fetchmail:
    image: mailu/fetchmail:${VERSION}
    restart: always
    labels: 
     io.rancher.container.pull_image: always
     com.docker.compose.service: fetchmail
    environment:
     BIND_ADDRESS4: ${BIND_ADDRESS4}
     COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
     DOMAIN: ${DOMAIN}
     ADMIN: ${EXPOSE_ADMIN}
     FETCHMAIL_DELAY: ${FETCHMAIL_DELAY}
     HOSTNAMES: ${HOSTNAMES}
     MESSAGE_SIZE_LIMIT: ${MESSAGE_SIZE_LIMIT}
     POSTMASTER: ${POSTMASTER}
     RELAYHOST: ${RELAYHOST}
     RELAYNETS: ${RELAYNETS}
     ROOT: ${ROOT}
     SECRET_KEY: ${SECRET_KEY}
     VERSION: ${VERSION}
     WEBMAIL: ${WEBMAIL}
     WEBDAV: ${WEBDAV}
     TLS_FLAVOR: ${TLS_FLAVOR}
     PASSWORD_SCHEME: ${PASSWORD_SCHEME}
     RECIPIENT_DELIMITER: ${RECIPIENT_DELIMITER}
     AUTH_RATELIMIT: ${AUTH_RATELIMIT}
     DISABLE_STATISTICS: "true"
     DMARC_RUA: postmaster
     DMARC_RUF: postmaster
     WELCOME: "false"
     WEB_ADMIN: "/admin"
     WEB_WEBMAIL: "/webmail"
    volumes:
      - "${ROOT}/data:/data"
