version: '2'
.catalog:
 name: "Nagios"
 minimun_rancher_version: 1.2.0
 version: "v0.0.1"
 questions:
  - variable: ROOT
    label: "Root Path"
    description: "Set this to the path where Nagios data and configuration is stored"
    default: "/nagios"
    required: true
    type: string
  - variable: VERSION
    label: "Nagios Version"
    description: "Nagios version to run (4.2.4, 4.3.1, etc. or latest)"
    default: "latest"
    required: true
    type: string
  - variable: FQDN
    label: "Nagios FQDN"
    description: "FQDN for this Nagios instance"
    default: "nagios.example.com"
    required: true
    type: string
  - variable: TIMEZONE
    label: "Nagios Timezone"
    description: "Timezone for Nagios.  use_timezone in nagios.cfg should match"
    default: "UTC"
    required: true
    type: string
nagios:
  scale: 1
  start_on_create: true
  health_check:
    healthy_threshold: 2
    response_timeout: 2000
    port: 80
    unhealthy_threshold: 3
    initializing_timeout: 60000
    interval: 2000
    strategy: recreate
    reinitializing_timeout: 60000
