consul-conf:
  image: romracer/consul-config:latest
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
  volumes_from:
    - consul
  net: "container:consul"
consul-registrator:
  image: gliderlabs/registrator:latest
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
    io.rancher.container.dns: 'true'
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  net: host
  command:
    - consul://consul:8500
consul:
  image: romracer/consul:latest
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
    io.rancher.scheduler.global: 'true'
    io.rancher.sidekicks: consul-conf,consul-registrator
  volumes:
    - /consul/config
    - /consul/data
