consul-conf:
  image: romracer/consul-config:latest
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
  volumes_from:
    - consul
  net: "container:consul"
consul-registrator:
  image: romracer/rancher-registrator:latest
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
    io.rancher.container.dns: 'true'
    io.rancher.container.network: 'false'
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    CONSUL_HTTP_TOKEN: "${master_token}"
    LOCAL_CONSUL_AGENT: "http://consul:8500"
  net: host
consul:
  image: romracer/consul:latest
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
    io.rancher.scheduler.global: 'true'
    io.rancher.sidekicks: consul-conf,consul-registrator
  volumes:
    - /consul/config
    - /consul/data
  ports:
    - 8500:8500/tcp
