version: '2'
volumes:
  ${consul_data}:
    external: true
    driver: ${volume_driver}
services:
  consul:
    image: romracer/consul
    volumes:
    - /opt/rancher/config
    - /opt/rancher/ssl
    - ${consul_data}:/var/consul
    labels:
      io.rancher.container.pull_image: always
      io.rancher.sidekicks: consul-conf
  consul-conf:
    image: romracer/consul-config
    network_mode: container:consul
    volumes_from:
    - consul
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
