consul-conf:
  image: romracer/consul-config
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.pull_image: always
  volumes_from:
    - consul
  net: "container:consul"
consul:
  image: romracer/consul
  labels:
    io.rancher.sidekicks: consul-conf
    io.rancher.container.pull_image: always
  volumes:
    - ${consul_ssl}:/opt/rancher/ssl
    - ${consul_config}:/opt/rancher/config
    - ${consul_data}:/var/consul
  volume_driver: ${volume_driver}
