.catalog:
  name: "vmdk"
  version: "0.10-rancher1"
  description: |
    vSphere - Docker volume plugin
  minimum_rancher_version: "v1.1.999"
vmdk-driver:
  storage_driver:
    name: vmdk
    scope: environment
    volume_access_mode: multiHostRW
