name: Mailu
description: "Insular email distribution - email server as Docker images"
version: v0.0.3
category: Mail
maintainer: AdrienM
license: MIT License
projectURl: "https://github.com/Mailu/Mailu"
